const asyncHandler = require('../middleware/asyncHandler');

const SCHEMES = [
    {
        id: 'pm-kisan',
        name: 'PM-KISAN',
        nameHindi: 'पीएम-किसान',
        fullName: 'Pradhan Mantri Kisan Samman Nidhi',
        fullNameHindi: 'प्रधानमंत्री किसान सम्मान निधि',
        emoji: '💰',
        category: 'Income Support',
        categoryHindi: 'आय सहायता',
        benefit: '₹6,000/year direct cash transfer in 3 instalments',
        benefitHindi: '₹6,000/वर्ष सीधे बैंक खाते में 3 किस्तों में',
        eligibility: 'All landholding farmer families with cultivable land',
        eligibilityHindi: 'सभी कृषक परिवार जिनके पास खेती योग्य भूमि है',
        states: 'all',
        ministry: 'कृषि एवं किसान कल्याण मंत्रालय',
        applyUrl: 'https://pmkisan.gov.in',
        documents: ['Aadhaar Card', 'Land Records', 'Bank Account'],
        documentsHindi: ['आधार कार्ड', 'भूमि रिकॉर्ड', 'बैंक खाता'],
        deadline: 'Ongoing – Register anytime',
        deadlineHindi: 'चालू – कभी भी पंजीकरण करें',
        featured: true,
    },
    {
        id: 'pmfby',
        name: 'PMFBY',
        nameHindi: 'पीएमएफबीवाई',
        fullName: 'Pradhan Mantri Fasal Bima Yojana',
        fullNameHindi: 'प्रधानमंत्री फसल बीमा योजना',
        emoji: '🛡️',
        category: 'Insurance',
        categoryHindi: 'बीमा',
        benefit: 'Crop insurance at 1.5–5% premium. Full compensation for crop loss',
        benefitHindi: '1.5–5% प्रीमियम पर फसल बीमा। फसल हानि पर पूर्ण मुआवजा',
        eligibility: 'All farmers growing notified crops. Mandatory for loanee farmers',
        eligibilityHindi: 'सूचित फसल उगाने वाले सभी किसान। ऋण लेने वाले किसानों के लिए अनिवार्य',
        states: 'all',
        ministry: 'कृषि एवं किसान कल्याण मंत्रालय',
        applyUrl: 'https://pmfby.gov.in',
        documents: ['Aadhaar Card', 'Land Records', 'Bank Account', 'Crop Sowing Certificate'],
        documentsHindi: ['आधार कार्ड', 'भूमि रिकॉर्ड', 'बैंक खाता', 'फसल बुवाई प्रमाण पत्र'],
        deadline: 'Before crop sowing (Kharif: July, Rabi: December)',
        deadlineHindi: 'फसल बुवाई से पहले (खरीफ: जुलाई, रबी: दिसंबर)',
        featured: true,
    },
    {
        id: 'kcc',
        name: 'Kisan Credit Card',
        nameHindi: 'किसान क्रेडिट कार्ड',
        fullName: 'Kisan Credit Card (KCC) Scheme',
        fullNameHindi: 'किसान क्रेडिट कार्ड (केसीसी) योजना',
        emoji: '💳',
        category: 'Credit & Loans',
        categoryHindi: 'ऋण एवं कर्ज',
        benefit: 'Short-term crop loans at 4% interest (7% minus 3% interest subvention)',
        benefitHindi: '4% ब्याज दर पर अल्पकालिक फसल ऋण (7% में से 3% सरकारी छूट)',
        eligibility: 'All farmers, sharecroppers, tenant farmers & SHGs',
        eligibilityHindi: 'सभी किसान, बटाईदार, काश्तकार किसान और स्वयं सहायता समूह',
        states: 'all',
        ministry: 'कृषि एवं किसान कल्याण मंत्रालय / आरबीआई',
        applyUrl: 'https://www.nabard.org/content.aspx?id=590',
        documents: ['Aadhaar Card', 'Land Records', 'Passport Photo', 'Bank Account'],
        documentsHindi: ['आधार कार्ड', 'भूमि रिकॉर्ड', 'पासपोर्ट फोटो', 'बैंक खाता'],
        deadline: 'Ongoing – Apply at any bank branch',
        deadlineHindi: 'चालू – किसी भी बैंक शाखा में आवेदन करें',
        featured: true,
    },
    {
        id: 'pmksy',
        name: 'PMKSY',
        nameHindi: 'पीएमकेएसवाई',
        fullName: 'Pradhan Mantri Krishi Sinchayee Yojana',
        fullNameHindi: 'प्रधानमंत्री कृषि सिंचाई योजना',
        emoji: '💧',
        category: 'Irrigation',
        categoryHindi: 'सिंचाई',
        benefit: 'Subsidy on drip & sprinkler irrigation. "Har Khet Ko Pani, More Crop Per Drop"',
        benefitHindi: 'ड्रिप और स्प्रिंकलर सिंचाई पर सब्सिडी। "हर खेत को पानी, प्रति बूंद अधिक फसल"',
        eligibility: 'Individual & group farmers. SHGs, cooperatives, NGOs',
        eligibilityHindi: 'व्यक्तिगत और समूह किसान। स्वयं सहायता समूह, सहकारी संस्थाएं, एनजीओ',
        states: 'all',
        ministry: 'जल शक्ति एवं कृषि मंत्रालय',
        applyUrl: 'https://pmksy.gov.in',
        documents: ['Aadhaar Card', 'Land Records', 'Bank Account'],
        documentsHindi: ['आधार कार्ड', 'भूमि रिकॉर्ड', 'बैंक खाता'],
        deadline: 'Ongoing – Apply at district agriculture office',
        deadlineHindi: 'चालू – जिला कृषि कार्यालय में आवेदन करें',
        featured: false,
    },
    {
        id: 'soil-health-card',
        name: 'Soil Health Card',
        nameHindi: 'मृदा स्वास्थ्य कार्ड',
        fullName: 'Soil Health Card Scheme',
        fullNameHindi: 'मृदा स्वास्थ्य कार्ड योजना',
        emoji: '🌱',
        category: 'Soil & Technology',
        categoryHindi: 'मिट्टी एवं तकनीक',
        benefit: 'Free soil testing + personalized fertilizer recommendations to cut costs',
        benefitHindi: 'मुफ्त मिट्टी परीक्षण + लागत कम करने के लिए व्यक्तिगत उर्वरक सिफारिशें',
        eligibility: 'All farmers',
        eligibilityHindi: 'सभी किसान',
        states: 'all',
        ministry: 'कृषि एवं किसान कल्याण मंत्रालय',
        applyUrl: 'https://soilhealth.dac.gov.in',
        documents: ['Aadhaar Card', 'Land Details'],
        documentsHindi: ['आधार कार्ड', 'भूमि विवरण'],
        deadline: 'Ongoing – Apply at Krishi Vigyan Kendra',
        deadlineHindi: 'चालू – कृषि विज्ञान केंद्र में आवेदन करें',
        featured: false,
    },
    {
        id: 'pm-kusum',
        name: 'PM-KUSUM',
        nameHindi: 'पीएम-कुसुम',
        fullName: 'PM Kisan Urja Suraksha evam Utthaan Mahabhiyan',
        fullNameHindi: 'प्रधानमंत्री किसान ऊर्जा सुरक्षा एवं उत्थान महाभियान',
        emoji: '☀️',
        category: 'Solar & Energy',
        categoryHindi: 'सौर ऊर्जा',
        benefit: 'Up to 60% subsidy on solar pumps. Sell surplus solar electricity to grid',
        benefitHindi: 'सोलर पंपों पर 60% तक सब्सिडी। अतिरिक्त बिजली ग्रिड को बेचें और कमाई करें',
        eligibility: 'Farmers with agricultural land',
        eligibilityHindi: 'कृषि भूमि वाले किसान',
        states: 'all',
        ministry: 'नवीन एवं नवीकरणीय ऊर्जा मंत्रालय',
        applyUrl: 'https://pmkusum.mnre.gov.in',
        documents: ['Aadhaar Card', 'Land Records', 'Electricity Bill', 'Bank Account'],
        documentsHindi: ['आधार कार्ड', 'भूमि रिकॉर्ड', 'बिजली बिल', 'बैंक खाता'],
        deadline: 'Ongoing – Apply on state nodal agency portal',
        deadlineHindi: 'चालू – राज्य नोडल एजेंसी पोर्टल पर आवेदन करें',
        featured: true,
    },
    {
        id: 'pkvy',
        name: 'PKVY',
        nameHindi: 'पीकेवीवाई',
        fullName: 'Paramparagat Krishi Vikas Yojana',
        fullNameHindi: 'परम्परागत कृषि विकास योजना',
        emoji: '🌿',
        category: 'Organic Farming',
        categoryHindi: 'जैविक खेती',
        benefit: '₹50,000/hectare for organic farming over 3 years. Certification support',
        benefitHindi: '3 वर्षों में ₹50,000/हेक्टेयर जैविक खेती के लिए। प्रमाणीकरण सहायता',
        eligibility: 'Farmers willing to adopt organic farming in clusters of 50+ acres',
        eligibilityHindi: '50+ एकड़ के समूह में जैविक खेती अपनाने के इच्छुक किसान',
        states: 'all',
        ministry: 'कृषि एवं किसान कल्याण मंत्रालय',
        applyUrl: 'https://pgsindia-ncof.gov.in/PKVY/Index.aspx',
        documents: ['Aadhaar Card', 'Land Records', 'Group Formation Documents'],
        documentsHindi: ['आधार कार्ड', 'भूमि रिकॉर्ड', 'समूह गठन दस्तावेज'],
        deadline: 'Apply through State Agriculture Department',
        deadlineHindi: 'राज्य कृषि विभाग के माध्यम से आवेदन करें',
        featured: false,
    },
    {
        id: 'pmkmy',
        name: 'PM-KMY',
        nameHindi: 'पीएम-केएमवाई',
        fullName: 'Pradhan Mantri Kisan Maandhan Yojana',
        fullNameHindi: 'प्रधानमंत्री किसान मानधन योजना',
        emoji: '👴',
        category: 'Pension',
        categoryHindi: 'पेंशन',
        benefit: 'Guaranteed pension of ₹3,000/month after age 60',
        benefitHindi: '60 वर्ष की आयु के बाद ₹3,000/माह की गारंटीड पेंशन',
        eligibility: 'Small & marginal farmers aged 18–40 with land ≤ 2 hectares',
        eligibilityHindi: '18–40 वर्ष के छोटे व सीमांत किसान जिनके पास ≤ 2 हेक्टेयर भूमि है',
        states: 'all',
        ministry: 'कृषि एवं किसान कल्याण मंत्रालय',
        applyUrl: 'https://maandhan.in',
        documents: ['Aadhaar Card', 'Land Records', 'Bank Account'],
        documentsHindi: ['आधार कार्ड', 'भूमि रिकॉर्ड', 'बैंक खाता'],
        deadline: 'Ongoing – Apply at CSC/Village Level Entrepreneur',
        deadlineHindi: 'चालू – सीएससी/ग्राम स्तरीय उद्यमी के पास आवेदन करें',
        featured: false,
    },
    {
        id: 'enam',
        name: 'e-NAM',
        nameHindi: 'ई-नाम',
        fullName: 'National Agriculture Market',
        fullNameHindi: 'राष्ट्रीय कृषि बाजार',
        emoji: '📱',
        category: 'Market Access',
        categoryHindi: 'बाजार पहुंच',
        benefit: 'Sell crop online across 1000+ mandis. Better prices, no middlemen',
        benefitHindi: '1000+ मंडियों में ऑनलाइन फसल बेचें। बेहतर दाम, बिना बिचौलिए के',
        eligibility: 'All farmers registered in any e-NAM mandi',
        eligibilityHindi: 'किसी भी ई-नाम मंडी में पंजीकृत सभी किसान',
        states: 'all',
        ministry: 'कृषि एवं किसान कल्याण मंत्रालय',
        applyUrl: 'https://enam.gov.in',
        documents: ['Aadhaar Card', 'Bank Account', 'Mobile Number'],
        documentsHindi: ['आधार कार्ड', 'बैंक खाता', 'मोबाइल नंबर'],
        deadline: 'Ongoing – Register online or at nearest mandi',
        deadlineHindi: 'चालू – ऑनलाइन या नजदीकी मंडी में पंजीकरण करें',
        featured: false,
    },
    {
        id: 'rkvy',
        name: 'RKVY-RAFTAAR',
        nameHindi: 'आरकेवीवाई-रफ्तार',
        fullName: 'Rashtriya Krishi Vikas Yojana',
        fullNameHindi: 'राष्ट्रीय कृषि विकास योजना',
        emoji: '🚀',
        category: 'Development',
        categoryHindi: 'विकास',
        benefit: 'Grants for agricultural infrastructure, storage, market development',
        benefitHindi: 'कृषि बुनियादी ढांचे, भंडारण, बाजार विकास के लिए अनुदान',
        eligibility: 'Farmers, FPOs, cooperatives, state govts. Agri-startups get seed funding',
        eligibilityHindi: 'किसान, एफपीओ, सहकारी संस्थाएं, राज्य सरकारें। कृषि स्टार्टअप को बीज निधि',
        states: 'all',
        ministry: 'कृषि एवं किसान कल्याण मंत्रालय',
        applyUrl: 'https://rkvy.nic.in',
        documents: ['Project Proposal', 'Land Records', 'Registration Certificate'],
        documentsHindi: ['परियोजना प्रस्ताव', 'भूमि रिकॉर्ड', 'पंजीकरण प्रमाण पत्र'],
        deadline: 'Apply through State Agriculture Department',
        deadlineHindi: 'राज्य कृषि विभाग के माध्यम से आवेदन करें',
        featured: false,
    },
    {
        id: 'agri-infra-fund',
        name: 'AIF',
        nameHindi: 'एआईएफ',
        fullName: 'Agriculture Infrastructure Fund',
        fullNameHindi: 'कृषि अवसंरचना निधि',
        emoji: '🏗️',
        category: 'Credit & Loans',
        categoryHindi: 'ऋण एवं कर्ज',
        benefit: '₹1 lakh crore fund at 3% interest subsidy for post-harvest infra & storage',
        benefitHindi: '₹1 लाख करोड़ की निधि, 3% ब्याज सब्सिडी, फसल-पश्चात बुनियादी ढांचे और भंडारण के लिए',
        eligibility: 'Farmers, FPOs, PACS, Agri-entrepreneurs, SHGs',
        eligibilityHindi: 'किसान, एफपीओ, पैक्स, कृषि उद्यमी, स्वयं सहायता समूह',
        states: 'all',
        ministry: 'कृषि एवं किसान कल्याण मंत्रालय',
        applyUrl: 'https://agriinfra.dac.gov.in',
        documents: ['Aadhaar Card', 'Business Plan', 'Land Documents', 'Bank Account'],
        documentsHindi: ['आधार कार्ड', 'व्यवसाय योजना', 'भूमि दस्तावेज', 'बैंक खाता'],
        deadline: 'Ongoing – Apply on AIF portal',
        deadlineHindi: 'चालू – एआईएफ पोर्टल पर आवेदन करें',
        featured: false,
    },
    {
        id: 'nfsm',
        name: 'NFSM',
        nameHindi: 'एनएफएसएम',
        fullName: 'National Food Security Mission',
        fullNameHindi: 'राष्ट्रीय खाद्य सुरक्षा मिशन',
        emoji: '🌾',
        category: 'Development',
        categoryHindi: 'विकास',
        benefit: 'Subsidised seeds, fertilizers, farm equipment for wheat/rice/pulses/oilseeds',
        benefitHindi: 'गेहूं/चावल/दलहन/तिलहन के लिए सब्सिडीयुक्त बीज, उर्वरक, कृषि उपकरण',
        eligibility: 'Farmers in targeted districts for rice, wheat, pulses, oilseeds, maize',
        eligibilityHindi: 'धान, गेहूं, दलहन, तिलहन, मक्का के लिए चयनित जिलों के किसान',
        states: 'all',
        ministry: 'कृषि एवं किसान कल्याण मंत्रालय',
        applyUrl: 'https://nfsm.gov.in',
        documents: ['Aadhaar Card', 'Land Records'],
        documentsHindi: ['आधार कार्ड', 'भूमि रिकॉर्ड'],
        deadline: 'Apply through District Agriculture Office',
        deadlineHindi: 'जिला कृषि कार्यालय के माध्यम से आवेदन करें',
        featured: false,
    },
    {
        id: 'mksp',
        name: 'MKSP',
        nameHindi: 'एमकेएसपी',
        fullName: 'Mahila Kisan Sashaktikaran Pariyojana',
        fullNameHindi: 'महिला किसान सशक्तिकरण परियोजना',
        emoji: '👩‍🌾',
        category: 'Women Farmers',
        categoryHindi: 'महिला किसान',
        benefit: 'Training, skill development & financial support exclusively for women farmers',
        benefitHindi: 'महिला किसानों के लिए प्रशिक्षण, कौशल विकास और वित्तीय सहायता',
        eligibility: 'Women farmers, especially from BPL & tribal communities',
        eligibilityHindi: 'महिला किसान, विशेषकर बीपीएल और आदिवासी समुदायों से',
        states: 'all',
        ministry: 'ग्रामीण विकास मंत्रालय',
        applyUrl: 'https://aajeevika.gov.in',
        documents: ['Aadhaar Card', 'Land Records or Tenancy Certificate', 'SHG Membership'],
        documentsHindi: ['आधार कार्ड', 'भूमि रिकॉर्ड या किरायेदारी प्रमाण पत्र', 'स्वयं सहायता समूह सदस्यता'],
        deadline: 'Apply through Block Development Officer',
        deadlineHindi: 'खंड विकास अधिकारी के माध्यम से आवेदन करें',
        featured: false,
    },
    {
        id: 'kalia',
        name: 'KALIA',
        nameHindi: 'कालिया',
        fullName: 'Krushak Assistance for Livelihood & Income Augmentation',
        fullNameHindi: 'कृषक आजीविका एवं आय संवर्धन सहायता (ओडिशा)',
        emoji: '🌻',
        category: 'Income Support',
        categoryHindi: 'आय सहायता',
        benefit: '₹25,000 support for cultivation + ₹12,500 for non-farming activities (Odisha)',
        benefitHindi: 'खेती के लिए ₹25,000 + गैर-कृषि गतिविधियों के लिए ₹12,500 (ओडिशा)',
        eligibility: 'Small, marginal & landless farmers in Odisha',
        eligibilityHindi: 'ओडिशा में छोटे, सीमांत और भूमिहीन किसान',
        states: 'odisha',
        ministry: 'ओडिशा सरकार',
        applyUrl: 'https://kalia.co.in',
        documents: ['Aadhaar Card', 'Land Records', 'Bank Account'],
        documentsHindi: ['आधार कार्ड', 'भूमि रिकॉर्ड', 'बैंक खाता'],
        deadline: 'Ongoing – Register on KALIA portal',
        deadlineHindi: 'चालू – कालिया पोर्टल पर पंजीकरण करें',
        featured: false,
    },
    {
        id: 'ryss',
        name: 'Rythu Bandhu',
        nameHindi: 'रायतु बंधु',
        fullName: 'Rythu Bandhu Investment Support Scheme',
        fullNameHindi: 'रायतु बंधु निवेश सहायता योजना',
        emoji: '💚',
        category: 'Income Support',
        categoryHindi: 'आय सहायता',
        benefit: '₹10,000/acre/year direct investment support for Telangana farmers',
        benefitHindi: 'तेलंगाना किसानों के लिए ₹10,000/एकड़/वर्ष प्रत्यक्ष निवेश सहायता',
        eligibility: 'All land-owning farmers in Telangana (per season: ₹5,000/acre)',
        eligibilityHindi: 'तेलंगाना में सभी भूमि-स्वामी किसान (प्रति सीजन: ₹5,000/एकड़)',
        states: 'telangana',
        ministry: 'तेलंगाना सरकार',
        applyUrl: 'https://rythubandhu.telangana.gov.in',
        documents: ['Aadhaar Card', 'Pattadar Passbook (Land Record)', 'Bank Account'],
        documentsHindi: ['आधार कार्ड', 'पट्टेदार पासबुक (भूमि रिकॉर्ड)', 'बैंक खाता'],
        deadline: 'Bi-annually before each crop season',
        deadlineHindi: 'प्रत्येक फसल मौसम से पहले दो बार वार्षिक',
        featured: false,
    },
    {
        id: 'atal-bhujal',
        name: 'Atal Bhujal Yojana',
        nameHindi: 'अटल भूजल योजना',
        fullName: 'Atal Bhujal Yojana',
        fullNameHindi: 'अटल भूजल योजना',
        emoji: '🏞️',
        category: 'Irrigation',
        categoryHindi: 'सिंचाई',
        benefit: 'Community-based groundwater management. Panchayat incentives for water conservation',
        benefitHindi: 'सामुदायिक भूजल प्रबंधन। जल संरक्षण के लिए पंचायत प्रोत्साहन',
        eligibility: 'Farmers & panchayats in 7 water-stressed states',
        eligibilityHindi: '7 जल-संकटग्रस्त राज्यों में किसान और पंचायतें',
        states: 'all',
        ministry: 'जल शक्ति मंत्रालय',
        applyUrl: 'https://atalbhujal.gov.in',
        documents: ['Aadhaar Card', 'Land Records'],
        documentsHindi: ['आधार कार्ड', 'भूमि रिकॉर्ड'],
        deadline: 'Apply through Gram Panchayat',
        deadlineHindi: 'ग्राम पंचायत के माध्यम से आवेदन करें',
        featured: false,
    },
];

const CATEGORIES = [...new Set(SCHEMES.map(s => s.category))];

const getSchemes = asyncHandler(async (req, res) => {
    const { category = '', state = '', search = '', featured = '' } = req.query;
    let filtered = [...SCHEMES];

    if (category) filtered = filtered.filter(s => s.category.toLowerCase() === category.toLowerCase());
    if (state && state !== 'all') filtered = filtered.filter(s => s.states === 'all' || s.states.toLowerCase().includes(state.toLowerCase()));
    if (search) {
        const q = search.toLowerCase();
        filtered = filtered.filter(s =>
            s.name.toLowerCase().includes(q) ||
            s.fullName.toLowerCase().includes(q) ||
            s.benefit.toLowerCase().includes(q) ||
            s.category.toLowerCase().includes(q) ||
            s.nameHindi?.includes(q) ||
            s.benefitHindi?.includes(q)
        );
    }
    if (featured === 'true') filtered = filtered.filter(s => s.featured);

    res.status(200).json({ success: true, count: filtered.length, categories: CATEGORIES, data: filtered });
});

module.exports = { getSchemes };
